"""Thin seam over the Anthropic Messages API so tests can inject a fake.

The model name comes from config (ANTHROPIC_MODEL) so cheaper models can be
A/B tested without code changes.
"""
from typing import Protocol

from core.config import settings


class LLMClient(Protocol):
    def complete(self, system_prompt: str, user_prompt: str) -> str:
        """Return the model's text output. Raise LLMError on API failure/refusal."""
        ...


class LLMError(Exception):
    pass


class StubLLM:
    """Deterministic offline stand-in used by the test harness — exercises the
    whole pipeline (prompt assembly, parsing, review UI) without an API key."""

    def complete(self, system_prompt: str, user_prompt: str) -> str:
        import json
        import re

        subject = ""
        email_id = 0
        for line in user_prompt.splitlines():
            if line.startswith("Subject: "):
                subject = line.removeprefix("Subject: ").strip()
            elif line.startswith("source_email_id: "):
                email_id = int(line.removeprefix("source_email_id: ").strip() or 0)
        board = re.search(r"# Board: (\S+)", system_prompt)
        return json.dumps({
            "summary": (subject or "Untitled request")[:100],
            "description": f"[stub draft — offline harness]\n\n{user_prompt.split(chr(10) * 2, 1)[-1][:1500]}",
            "issue_type": "Task",
            "project_key": board.group(1) if board else "MSA",
            "priority": "Medium",
            "labels": ["needs-triage"],
            "acceptance_criteria": ["Operator replaces this stub draft before approving"],
            "confidence": 0.1,
            "rationale": "Generated by the offline StubLLM; run with --live for a real draft.",
            "source_email_id": email_id,
        })


class AnthropicClient:
    def __init__(self, api_key: str | None = None, model: str | None = None):
        import anthropic

        self._client = anthropic.Anthropic(api_key=api_key or settings.anthropic_api_key)
        self.model = model or settings.anthropic_model

    def complete(self, system_prompt: str, user_prompt: str) -> str:
        import anthropic

        try:
            response = self._client.messages.create(
                model=self.model,
                max_tokens=2048,
                system=system_prompt,
                messages=[{"role": "user", "content": user_prompt}],
            )
        except anthropic.APIError as exc:
            raise LLMError(str(exc)) from exc
        # A refusal or empty result must surface for manual review, not crash.
        if response.stop_reason == "refusal" or not response.content:
            raise LLMError(f"model returned no usable content (stop_reason={response.stop_reason})")
        return "".join(block.text for block in response.content if block.type == "text")
